name: publish-dockerhub
on:
  push:
    branches:
      - 'master'
      - 'v*'
    tags:
      - 'v*'
  workflow_dispatch:
    inputs:
      image_tag:
        description: "tag of docker image"
        required: false 
        default: "latest"

jobs:
  publish-dockerhub:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and publish(push) with tags:[${{ github.ref_name }}]
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: cupen/protoc:${{ github.ref_name }}
        if: github.event_name == 'push'

      - name: Build and publish(manual) with tags:[${{ github.event.inputs.image_tag }}]
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: cupen/protoc:${{ github.event.inputs.image_tag }}
        if: github.event_name == 'workflow_dispatch'
